---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: reinierlabee
spec:
  serviceAccountName: flux-reconciler
  interval: 10m
  targetNamespace: reinierlabee
  chart:
    spec:
      chart: podinfo
      version: 6.0.2
      sourceRef:
        kind: HelmRepository
        name: podinfo
  values:
    # Default values for podinfo.
    replicaCount: 1
    logLevel: info
    ui:
      color: "#34577c"
      message: "This Helm Release is done with Flux"
      logo: ""

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      seccompProfile:
        type: RuntimeDefault

    acme:
      # You must replace this email address with your own.
      # Let's Encrypt will use this to contact you about expiring
      # certificates, and issues related to your account.
      email: reinier.labee@funatic.nl
      server: https://acme-staging-v02.api.letsencrypt.org/directory
      privateKeySecretRef:
        # Secret resource that will be used to store the account's private key.
        name: example-issuer-account-key
      # Add a single challenge solver, HTTP01 using nginx
      solvers:
      - http01:
          ingress:
            ingressClassName: nginx

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-production
      hosts:
        - host: reinierlabee.funatic.app.guida.io
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: podinfo-tls
          hosts:
            - reinierlabee.funatic.app.guida.io
